//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int ID { get; set; }
        public string Story_Name { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Story1 { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Rating { get; set; }
    }
}
